// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:            string;
    type:          string;
    place_type:    string[];
    relevance:     number;
    properties:    Properties;
    text_es:       string;
    place_name_es: string;
    text:          string;
    place_name:    string;
    center:        number[];
    geometry:      Geometry;
    context:       Context[];
    language_es?:  string;
    language?:     string;
}

export interface Context {
    id:           ID;
    wikidata?:    Wikidata;
    text_es:      string;
    language_es?: Language;
    text:         string;
    language?:    Language;
    short_code?:  ShortCode;
}

export enum ID {
    Country5596864799773450 = "country.5596864799773450",
    Place600223 = "place.600223",
    Postcode10079903 = "postcode.10079903",
    Region10307146222929210 = "region.10307146222929210",
}

export enum Language {
    Es = "es",
}

export enum ShortCode {
    MX = "mx",
    MXAgu = "MX-AGU",
}

export enum Wikidata {
    Q200805 = "Q200805",
    Q79952 = "Q79952",
    Q96 = "Q96",
}

export interface Geometry {
    coordinates: number[];
    type:        string;
}

export interface Properties {
    foursquare: string;
    landmark:   boolean;
    address:    string;
    category:   string;
}
